<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<AssemblyName>RzR.Core.CodeSource.Tests</AssemblyName>
		<RootNamespace>Tests</RootNamespace>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
		<PackageReference Include="coverlet.collector" Version="3.0.2" />
		<PackageReference Include="YamlDotNet" Version="13.1.1" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<PackageDownload Include="NETStandard.Library.Ref" Version="[2.1.0]" />
		<None Include="$(NuGetPackageRoot)netstandard.library.ref\2.1.0\ref\netstandard2.1\netstandard.dll"
			  Link="ScanFailRefs\netstandard.dll"
			  CopyToOutputDirectory="PreserveNewest"
			  Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\CodeSource\CodeSource.csproj" />
		<ProjectReference Include="..\TempLib\TempLib.csproj" />
		<ProjectReference Include="..\TempLib.Fixtures\TempLib.Fixtures.csproj" />
		<ProjectReference Include="..\TempLib.NoSymbol\TempLib.NoSymbol.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(BuildingInsideVisualStudio)' != 'true' And '$(NCrunch)' != '1'">
		<ProjectReference Include="..\..\CodeSource\CodeSource.csproj"
						  ReferenceOutputAssembly="false"
						  SkipGetTargetFrameworkProperties="true" />
	</ItemGroup>

	<PropertyGroup>
		<CodeSourceBinRoot>$([MSBuild]::NormalizeDirectory('$(MSBuildProjectDirectory)', '..', '..', 'CodeSource', 'bin', '$(Configuration)'))</CodeSourceBinRoot>
		<CodeSourceBinRoot Condition="'$(NCrunch)' == '1' And '$(NCrunchOriginalProjectDir)' != ''">$([MSBuild]::NormalizeDirectory('$(NCrunchOriginalProjectDir)', '..', '..', 'CodeSource', 'bin', '$(Configuration)'))</CodeSourceBinRoot>
		<DefineConstants Condition="'$(NCrunch)' == '1'">$(DefineConstants);NCRUNCH</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyMetadata Include="CodeSourceBinRoot" Value="$(CodeSourceBinRoot)" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties BuildVersion_StartDate="2000/1/1" />
		</VisualStudio>
	</ProjectExtensions>

</Project>
